[versions]
androidGradlePlugin = "8.4.0-dev"
kotlin = "1.9.0"

[libraries]
android-gradlePlugin-api = { group = "com.android.tools.build", name = "gradle-api", version.ref = "androidGradlePlugin" }
errorprone = "com.google.errorprone:error_prone_annotations:2.3.2"
[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
